[package]
name = "codex_tool"
version = "0.1.1"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk.workspace = true
proto_pdk.workspace = true
serde.workspace = true
starbase_utils.workspace = true

[dev-dependencies]
proto_pdk_test_utils.workspace = true
tokio = { version = "1", features = ["full"] }
