name: Build & Release

permissions:
  contents: write

on:
  push:
    branches: ['main']
    tags: ['*-v[0-9]+.[0-9]+.[0-9]+']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Parse Tag
        run: |
          tag_name="${{ github.ref_name }}"
          project_name=$(echo "$tag_name" | cut -d '-' -f 1)
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1
          cache-all-crates: true
      - name: Install wabt
        run: |
          sudo apt update & sudo apt install -y wabt
      - name: Install binaryen
        run: |
          curl -fsSL https://github.com/WebAssembly/binaryen/releases/download/version_128/binaryen-version_128-x86_64-linux.tar.gz | tar xz -C /tmp
          echo "/tmp/binaryen-version_128/bin" >> $GITHUB_PATH
      - name: Build WASM
        run: cargo build --package "$PROJECT_NAME" --target wasm32-wasip1 --release
      - name: Optimize and Strip
        run: |
          input_path="target/wasm32-wasip1/release/${PROJECT_NAME}.wasm"
          output_path="out/${PROJECT_NAME}.wasm"
          mkdir -p out
          wasm-opt -Os "$input_path" -o "$output_path"
          wasm-strip "$output_path"
          echo "WASM_PATH=$output_path" >> $GITHUB_ENV
      - name: Generate SHA256 Checksum
        run: |
          sha256sum "$WASM_PATH" > "${WASM_PATH}.sha256"
      - name: Get Previous Tag
        uses: actions/github-script@v8
        id: previous-tag
        with:
          script: |
            const prefix = process.env.PROJECT_NAME;
            const regex = new RegExp(`^${prefix}-v\\d+\\.\\d+\\.\\d+$`);

            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const target = releases.find(r => !r.draft && regex.test(r.tag_name));

            if (target) {
              console.log(`Matched Release: ${target.tag_name} (ID: ${target.id})`);
              core.setOutput("tag_name", target.tag_name);
            } else {
              core.setFailed(`No release found matching pattern: ${prefix}-v*.*.*`);
            }
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: out/*
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          generateReleaseNotesPreviousTag: ${{ steps.previous-tag.outputs.tag_name }}
          skipIfReleaseExists: true
